<a href="https://colab.research.google.com/github/jorgefpont/hello-world/blob/master/test_notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This is a test

In [0]:
print("hello world!")

hello world!


In [4]:
import numpy as np
import pprint as pp

a = np.array([[1,2],[3,4],[6,6]])
b = np.array([[5],[10]])
c = np.dot(a,b)
print("a = \n",a)
print("b = \n",b)
print("c = \n",c)

a = 
 [[1 2]
 [3 4]
 [6 6]]
b = 
 [[ 5]
 [10]]
c = 
 [[25]
 [55]
 [90]]


In [16]:
z=np.zeros([3,4])
o=np.ones([4,3])
r=np.random.random_sample([3,4])
r=np.add(r, -0.5)
r=np.divide(r, 100)
print("zeros = \n", z)
print("ones = \n", o)
print("rand = \n", r)

zeros = 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones = 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
rand = 
 [[ 4.58625507e-03  1.38169422e-03  1.16565811e-03 -3.71196284e-03]
 [ 8.40611161e-04 -4.65585556e-04  6.75057575e-04  1.72365505e-03]
 [-1.92257918e-04 -9.97193426e-05 -2.18683373e-03 -2.46519792e-03]]
